# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        provider.facebook_user:
            id: facebook_user_provider

    firewalls:
        api_doc:
            pattern: ^/api/doc
            security: false

        secured_area:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: facebook_authenticator
            provider: provider.facebook_user
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
