parameters:
    my_user_provider.class: AppBundle\Security\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments:
            - '@fos_user.user_manager'
            - { facebook: facebookID }
