parameters:
    my_user_provider.class: AppBundle\Security\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments:
            - '@fos_user.user_manager'
            - { facebook: facebookID }

    facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator

    facebook_user_provider:
        class: AppBundle\Security\FacebookUserProvider
        arguments: ["@csa_guzzle.client.facebook_api", "@jms_serializer"]

    api_key_authenticator:
        class: AppBundle\Security\FacebookAuthenticator
        arguments: ["@router"]