parameters:
    #parameter_name: value

services:

    facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator

    facebook_user_provider:
        class: AppBundle\Security\FacebookUserProvider
        arguments: ["@csa_guzzle.client.facebook_api", "@jms_serializer"]

    app_bundle.command:
        class: AppBundle\DataFixtures\ORM\LoadingDatas
        arguments: [ "@doctrine.orm.entity_manager" ]
